# Generated by Django 5.1.7 on 2025-03-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Furniture'), ('automobiles', 'Automobiles'), ('books', 'Books')], max_length=100, null=True),
        ),
    ]
