# Generated by Django 5.1.7 on 2025-03-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
    ]
